# httpfs2
# Autogenerated from man page /usr/share/man/man1/httpfs2.1.gz
complete -c httpfs2 -s c -d 'Attempt to use the file ior device console for output after fork'
complete -c httpfs2 -s f -d 'Do not fork, stay in foreground'
complete -c httpfs2 -s t -d 'Use different timeout for connections.  Default \\*(Aq30\'s'

