# node
# Autogenerated from man page /usr/share/man/man1/node.1.gz
complete -c node -l experimental-shadow-realm -d 'Use this flag to enable ShadowRealm support'
complete -c node -l experimental-test-coverage -d 'Enable code coverage in the test runner'
complete -c node -l no-experimental-fetch -d 'Disable experimental support for the Fetch API'
complete -c node -l no-experimental-global-customevent -d 'Disable exposition of the CustomEvent on the global scope'
complete -c node -l no-experimental-global-webcrypto -d 'Disable exposition of the Web Crypto API on the global scope'
complete -c node -l no-extra-info-on-fatal-exception -d 'Hide extra information on fatal exception that causes exit'
complete -c node -l test-name-pattern -d 'A regular expression that configures the test runner to only execute tests wh…'

